//java
class HelloWorld {
   static {
      System.loadLibrary("helloworld");
   }
   public static native void print();
   public static  void main(String[] args) {
      print();
   }
}
//$export JAVA_HOME=/usr/lib/jvm/java
//$javac HelloWorld.java
//]$ls
HelloWorld.class  HelloWorld.java
//javac -h . HelloWorld.java
//$ls
HelloWorld.class  HelloWorld.h  HelloWorld.java
//$cat HelloWorld.h
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
//$vi HelloWorld.c
//$cat HelloWorld.c
#include<jni.h>
#include<stdio.h>
#include"HelloWorld.h"
JNIEXPORT void JNICALL Java_HelloWorld_print(JNIEnv *env, jclass c1) {
   printf("HelloWorld!!!!");
}
//$gcc -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" -fPIC -shared -o libhelloworld.so HelloWorld.c
//$java -Djava.library.path=. HelloWorld
HelloWorld!!!!
